### ISSUE TITLE
getData() should download data from S3 when possible

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/maap-py#28]
Related to https://github.com/MAAP-Project/maap-py/issues/27 and https://github.com/MAAP-Project/maap-documentation/pull/115, the granules `_location` field should by default use the S3 link if it exists in the metadata, so that `getData()` downloads from S3 and not the DAAC.

**Comment by chuckwondo** [comment]
@abarciauskas-bgse, this is already how this works. Are you seeing cases where this it not happening?

Note that if S3 download fails, the logic falls back to attempting to download via HTTPS, but as noted in #27, the logic converts the S3 URL to an HTTPS URL, rather than looking for an appropriate HTTPS URL within the metadata. This doesn't work because the "translation" from S3 to HTTPS does not produce the correct URL.

**Comment by abarciauskas-bgse** [comment]
As discussed in scrum, I think we have had slightly different experiences based on the order of the URLs returned in the CMR metadata. I'm assuming that if the S3 URL comes first, than this works as I would hope, in that the S3 access is used. However, if the HTTPS link comes before the S3 URL, then I believe the getData function will download over HTTPS. I _think_ S3 should be used by default regardless of the order of the URLs. So the function should find all GET DATA links and select S3 if it exists in those links.

**Comment by chuckwondo** [comment]
Ah, yes, that makes complete sense. At the moment, only the first URL is used, while the rest are ignored, so if the first URL is an S3 URL, S3 is used, but if an HTTPS URL is first, HTTPS is used.
